<<<<<<< HEAD
title: Nacho Kleinman Projects site
logo: /assets/img/profile.jpg
description: This website is Nacho Kleinman's personal projects site. A place to check and learn about his lasts projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme